using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.IO;

namespace Wookie.Master.Menu.Control
{
    public partial class ucMenu : DevExpress.XtraEditors.XtraUserControl
    {
        private Database.MenuDataContext dataContext = null;
        private ModulData modulData = null;

        public ucMenu(ModulData modulData)
        {
            InitializeComponent();
            this.modulData = modulData;
            dataContext = new Database.MenuDataContext(modulData.SqlConnectionClientDB);
            tsysClientBindingSource.DataSource = dataContext.tsysClient;
            
            // This line of code is generated by Data Source Configuration Wizard
            tsysClientElementBindingSource.DataSource = dataContext.tsysClient;
        }

        private void RefreshDataOnScreen()
        {
            Database.tsysClient c = (Database.tsysClient)tsysClientBindingSource.Current;
            tsysClientElementBindingSource.DataSource = c;                            
        }

        private void gridView1_SelectionChanged(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {
         
        }

        private void tsysClientBindingSource_CurrentChanged(object sender, EventArgs e)
        {
            RefreshDataOnScreen();
        }

        private void treeList1_AfterDragNode(object sender, DevExpress.XtraTreeList.AfterDragNodeEventArgs e)
        {
            dataContext.SubmitChanges();
        }
    }
}
