#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wookie.Menu.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BS_PM_Master")]
	public partial class MenuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void InserttsysUser(tsysUser instance);
    partial void UpdatetsysUser(tsysUser instance);
    partial void DeletetsysUser(tsysUser instance);
    partial void InserttsysCategory(tsysCategory instance);
    partial void UpdatetsysCategory(tsysCategory instance);
    partial void DeletetsysCategory(tsysCategory instance);
    partial void InserttsysClient(tsysClient instance);
    partial void UpdatetsysClient(tsysClient instance);
    partial void DeletetsysClient(tsysClient instance);
    partial void InserttsysModul(tsysModul instance);
    partial void UpdatetsysModul(tsysModul instance);
    partial void DeletetsysModul(tsysModul instance);
    partial void InserttsysModulGroup(tsysModulGroup instance);
    partial void UpdatetsysModulGroup(tsysModulGroup instance);
    partial void DeletetsysModulGroup(tsysModulGroup instance);
    partial void InserttsysSubCategory(tsysSubCategory instance);
    partial void UpdatetsysSubCategory(tsysSubCategory instance);
    partial void DeletetsysSubCategory(tsysSubCategory instance);
    partial void InserttsysClientElement(tsysClientElement instance);
    partial void UpdatetsysClientElement(tsysClientElement instance);
    partial void DeletetsysClientElement(tsysClientElement instance);
    #endregion
		
		public MenuDataContext() : 
				base(global::Wookie.Menu.Properties.Settings.Default.BS_PM_MasterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MenuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tsysUser> tsysUser
		{
			get
			{
				return this.GetTable<tsysUser>();
			}
		}
		
		public System.Data.Linq.Table<tsysCategory> tsysCategory
		{
			get
			{
				return this.GetTable<tsysCategory>();
			}
		}
		
		public System.Data.Linq.Table<tsysClient> tsysClient
		{
			get
			{
				return this.GetTable<tsysClient>();
			}
		}
		
		public System.Data.Linq.Table<tsysModul> tsysModul
		{
			get
			{
				return this.GetTable<tsysModul>();
			}
		}
		
		public System.Data.Linq.Table<tsysModulGroup> tsysModulGroup
		{
			get
			{
				return this.GetTable<tsysModulGroup>();
			}
		}
		
		public System.Data.Linq.Table<tsysSubCategory> tsysSubCategory
		{
			get
			{
				return this.GetTable<tsysSubCategory>();
			}
		}
		
		public System.Data.Linq.Table<v_Wookie_Menu_0000> v_Wookie_Menu_0000
		{
			get
			{
				return this.GetTable<v_Wookie_Menu_0000>();
			}
		}
		
		public System.Data.Linq.Table<tsysClientElement> tsysClientElement
		{
			get
			{
				return this.GetTable<tsysClientElement>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysUser")]
	public partial class tsysUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKUser;
		
		private System.Nullable<long> _FKContact;
		
		private string _Name;
		
		private string _Login;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _FKUserCreated;
		
		private System.Nullable<System.DateTime> _ChangedOn;
		
		private System.Nullable<long> _FKUserChangedOn;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKUserChanging(long value);
    partial void OnPKUserChanged();
    partial void OnFKContactChanging(System.Nullable<long> value);
    partial void OnFKContactChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnFKUserCreatedChanging(System.Nullable<long> value);
    partial void OnFKUserCreatedChanged();
    partial void OnChangedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnChangedOnChanged();
    partial void OnFKUserChangedOnChanging(System.Nullable<long> value);
    partial void OnFKUserChangedOnChanged();
    #endregion
		
		public tsysUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKUser", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKUser
		{
			get
			{
				return this._PKUser;
			}
			set
			{
				if ((this._PKUser != value))
				{
					this.OnPKUserChanging(value);
					this.SendPropertyChanging();
					this._PKUser = value;
					this.SendPropertyChanged("PKUser");
					this.OnPKUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKContact", DbType="BigInt")]
		public System.Nullable<long> FKContact
		{
			get
			{
				return this._FKContact;
			}
			set
			{
				if ((this._FKContact != value))
				{
					this.OnFKContactChanging(value);
					this.SendPropertyChanging();
					this._FKContact = value;
					this.SendPropertyChanged("FKContact");
					this.OnFKContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NVarChar(255)")]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserCreated", DbType="BigInt")]
		public System.Nullable<long> FKUserCreated
		{
			get
			{
				return this._FKUserCreated;
			}
			set
			{
				if ((this._FKUserCreated != value))
				{
					this.OnFKUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._FKUserCreated = value;
					this.SendPropertyChanged("FKUserCreated");
					this.OnFKUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangedOn
		{
			get
			{
				return this._ChangedOn;
			}
			set
			{
				if ((this._ChangedOn != value))
				{
					this.OnChangedOnChanging(value);
					this.SendPropertyChanging();
					this._ChangedOn = value;
					this.SendPropertyChanged("ChangedOn");
					this.OnChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserChangedOn", DbType="BigInt")]
		public System.Nullable<long> FKUserChangedOn
		{
			get
			{
				return this._FKUserChangedOn;
			}
			set
			{
				if ((this._FKUserChangedOn != value))
				{
					this.OnFKUserChangedOnChanging(value);
					this.SendPropertyChanging();
					this._FKUserChangedOn = value;
					this.SendPropertyChanged("FKUserChangedOn");
					this.OnFKUserChangedOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysCategory")]
	public partial class tsysCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKCategory;
		
		private System.Nullable<long> _FKModul;
		
		private System.Nullable<long> _FKExternal;
		
		private string _Name;
		
		private System.Data.Linq.Binary _Image;
		
		private System.Nullable<int> _SortOrder;
		
		private string _Assemblyname;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _FKUserCreated;
		
		private System.Nullable<System.DateTime> _ChangedOn;
		
		private System.Nullable<long> _FKUserChangedOn;
		
		private EntitySet<tsysSubCategory> _tsysSubCategory;
		
		private EntityRef<tsysModul> _tsysModul;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKCategoryChanging(long value);
    partial void OnPKCategoryChanged();
    partial void OnFKModulChanging(System.Nullable<long> value);
    partial void OnFKModulChanged();
    partial void OnFKExternalChanging(System.Nullable<long> value);
    partial void OnFKExternalChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnAssemblynameChanging(string value);
    partial void OnAssemblynameChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnFKUserCreatedChanging(System.Nullable<long> value);
    partial void OnFKUserCreatedChanged();
    partial void OnChangedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnChangedOnChanged();
    partial void OnFKUserChangedOnChanging(System.Nullable<long> value);
    partial void OnFKUserChangedOnChanged();
    #endregion
		
		public tsysCategory()
		{
			this._tsysSubCategory = new EntitySet<tsysSubCategory>(new Action<tsysSubCategory>(this.attach_tsysSubCategory), new Action<tsysSubCategory>(this.detach_tsysSubCategory));
			this._tsysModul = default(EntityRef<tsysModul>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKCategory", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKCategory
		{
			get
			{
				return this._PKCategory;
			}
			set
			{
				if ((this._PKCategory != value))
				{
					this.OnPKCategoryChanging(value);
					this.SendPropertyChanging();
					this._PKCategory = value;
					this.SendPropertyChanged("PKCategory");
					this.OnPKCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKModul", DbType="BigInt")]
		public System.Nullable<long> FKModul
		{
			get
			{
				return this._FKModul;
			}
			set
			{
				if ((this._FKModul != value))
				{
					if (this._tsysModul.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKModulChanging(value);
					this.SendPropertyChanging();
					this._FKModul = value;
					this.SendPropertyChanged("FKModul");
					this.OnFKModulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKExternal", DbType="BigInt")]
		public System.Nullable<long> FKExternal
		{
			get
			{
				return this._FKExternal;
			}
			set
			{
				if ((this._FKExternal != value))
				{
					this.OnFKExternalChanging(value);
					this.SendPropertyChanging();
					this._FKExternal = value;
					this.SendPropertyChanged("FKExternal");
					this.OnFKExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assemblyname", DbType="NVarChar(255)")]
		public string Assemblyname
		{
			get
			{
				return this._Assemblyname;
			}
			set
			{
				if ((this._Assemblyname != value))
				{
					this.OnAssemblynameChanging(value);
					this.SendPropertyChanging();
					this._Assemblyname = value;
					this.SendPropertyChanged("Assemblyname");
					this.OnAssemblynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserCreated", DbType="BigInt")]
		public System.Nullable<long> FKUserCreated
		{
			get
			{
				return this._FKUserCreated;
			}
			set
			{
				if ((this._FKUserCreated != value))
				{
					this.OnFKUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._FKUserCreated = value;
					this.SendPropertyChanged("FKUserCreated");
					this.OnFKUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangedOn
		{
			get
			{
				return this._ChangedOn;
			}
			set
			{
				if ((this._ChangedOn != value))
				{
					this.OnChangedOnChanging(value);
					this.SendPropertyChanging();
					this._ChangedOn = value;
					this.SendPropertyChanged("ChangedOn");
					this.OnChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserChangedOn", DbType="BigInt")]
		public System.Nullable<long> FKUserChangedOn
		{
			get
			{
				return this._FKUserChangedOn;
			}
			set
			{
				if ((this._FKUserChangedOn != value))
				{
					this.OnFKUserChangedOnChanging(value);
					this.SendPropertyChanging();
					this._FKUserChangedOn = value;
					this.SendPropertyChanged("FKUserChangedOn");
					this.OnFKUserChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysCategory_tsysSubCategory", Storage="_tsysSubCategory", ThisKey="PKCategory", OtherKey="FKCategory")]
		public EntitySet<tsysSubCategory> tsysSubCategory
		{
			get
			{
				return this._tsysSubCategory;
			}
			set
			{
				this._tsysSubCategory.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysModul_tsysCategory", Storage="_tsysModul", ThisKey="FKModul", OtherKey="PKModul", IsForeignKey=true)]
		public tsysModul tsysModul
		{
			get
			{
				return this._tsysModul.Entity;
			}
			set
			{
				tsysModul previousValue = this._tsysModul.Entity;
				if (((previousValue != value) 
							|| (this._tsysModul.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tsysModul.Entity = null;
						previousValue.tsysCategory.Remove(this);
					}
					this._tsysModul.Entity = value;
					if ((value != null))
					{
						value.tsysCategory.Add(this);
						this._FKModul = value.PKModul;
					}
					else
					{
						this._FKModul = default(Nullable<long>);
					}
					this.SendPropertyChanged("tsysModul");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tsysSubCategory(tsysSubCategory entity)
		{
			this.SendPropertyChanging();
			entity.tsysCategory = this;
		}
		
		private void detach_tsysSubCategory(tsysSubCategory entity)
		{
			this.SendPropertyChanging();
			entity.tsysCategory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysClient")]
	public partial class tsysClient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKClient;
		
		private string _Name;
		
		private System.Nullable<int> _SortOrder;
		
		private string _Datasource;
		
		private string _InitialCatalog;
		
		private System.Nullable<bool> _PersistSecurityInfo;
		
		private string _UserID;
		
		private string _Password;
		
		private System.Data.Linq.Binary _Image;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _FKUserCreated;
		
		private System.Nullable<System.DateTime> _ChangedOn;
		
		private System.Nullable<long> _FKUserChangedOn;
		
		private EntitySet<tsysModulGroup> _tsysModulGroup;
		
		private EntitySet<tsysClientElement> _tsysClientElement;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKClientChanging(long value);
    partial void OnPKClientChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnDatasourceChanging(string value);
    partial void OnDatasourceChanged();
    partial void OnInitialCatalogChanging(string value);
    partial void OnInitialCatalogChanged();
    partial void OnPersistSecurityInfoChanging(System.Nullable<bool> value);
    partial void OnPersistSecurityInfoChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnFKUserCreatedChanging(System.Nullable<long> value);
    partial void OnFKUserCreatedChanged();
    partial void OnChangedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnChangedOnChanged();
    partial void OnFKUserChangedOnChanging(System.Nullable<long> value);
    partial void OnFKUserChangedOnChanged();
    #endregion
		
		public tsysClient()
		{
			this._tsysModulGroup = new EntitySet<tsysModulGroup>(new Action<tsysModulGroup>(this.attach_tsysModulGroup), new Action<tsysModulGroup>(this.detach_tsysModulGroup));
			this._tsysClientElement = new EntitySet<tsysClientElement>(new Action<tsysClientElement>(this.attach_tsysClientElement), new Action<tsysClientElement>(this.detach_tsysClientElement));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKClient", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKClient
		{
			get
			{
				return this._PKClient;
			}
			set
			{
				if ((this._PKClient != value))
				{
					this.OnPKClientChanging(value);
					this.SendPropertyChanging();
					this._PKClient = value;
					this.SendPropertyChanged("PKClient");
					this.OnPKClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datasource", DbType="NVarChar(255)")]
		public string Datasource
		{
			get
			{
				return this._Datasource;
			}
			set
			{
				if ((this._Datasource != value))
				{
					this.OnDatasourceChanging(value);
					this.SendPropertyChanging();
					this._Datasource = value;
					this.SendPropertyChanged("Datasource");
					this.OnDatasourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitialCatalog", DbType="NVarChar(255)")]
		public string InitialCatalog
		{
			get
			{
				return this._InitialCatalog;
			}
			set
			{
				if ((this._InitialCatalog != value))
				{
					this.OnInitialCatalogChanging(value);
					this.SendPropertyChanging();
					this._InitialCatalog = value;
					this.SendPropertyChanged("InitialCatalog");
					this.OnInitialCatalogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersistSecurityInfo", DbType="Bit")]
		public System.Nullable<bool> PersistSecurityInfo
		{
			get
			{
				return this._PersistSecurityInfo;
			}
			set
			{
				if ((this._PersistSecurityInfo != value))
				{
					this.OnPersistSecurityInfoChanging(value);
					this.SendPropertyChanging();
					this._PersistSecurityInfo = value;
					this.SendPropertyChanged("PersistSecurityInfo");
					this.OnPersistSecurityInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(255)")]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(255)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserCreated", DbType="BigInt")]
		public System.Nullable<long> FKUserCreated
		{
			get
			{
				return this._FKUserCreated;
			}
			set
			{
				if ((this._FKUserCreated != value))
				{
					this.OnFKUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._FKUserCreated = value;
					this.SendPropertyChanged("FKUserCreated");
					this.OnFKUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangedOn
		{
			get
			{
				return this._ChangedOn;
			}
			set
			{
				if ((this._ChangedOn != value))
				{
					this.OnChangedOnChanging(value);
					this.SendPropertyChanging();
					this._ChangedOn = value;
					this.SendPropertyChanged("ChangedOn");
					this.OnChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserChangedOn", DbType="BigInt")]
		public System.Nullable<long> FKUserChangedOn
		{
			get
			{
				return this._FKUserChangedOn;
			}
			set
			{
				if ((this._FKUserChangedOn != value))
				{
					this.OnFKUserChangedOnChanging(value);
					this.SendPropertyChanging();
					this._FKUserChangedOn = value;
					this.SendPropertyChanged("FKUserChangedOn");
					this.OnFKUserChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysClient_tsysModulGroup", Storage="_tsysModulGroup", ThisKey="PKClient", OtherKey="FKClient")]
		public EntitySet<tsysModulGroup> tsysModulGroup
		{
			get
			{
				return this._tsysModulGroup;
			}
			set
			{
				this._tsysModulGroup.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysClient_tsysClientElement", Storage="_tsysClientElement", ThisKey="PKClient", OtherKey="FKClient")]
		public EntitySet<tsysClientElement> tsysClientElement
		{
			get
			{
				return this._tsysClientElement;
			}
			set
			{
				this._tsysClientElement.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tsysModulGroup(tsysModulGroup entity)
		{
			this.SendPropertyChanging();
			entity.tsysClient = this;
		}
		
		private void detach_tsysModulGroup(tsysModulGroup entity)
		{
			this.SendPropertyChanging();
			entity.tsysClient = null;
		}
		
		private void attach_tsysClientElement(tsysClientElement entity)
		{
			this.SendPropertyChanging();
			entity.tsysClient = this;
		}
		
		private void detach_tsysClientElement(tsysClientElement entity)
		{
			this.SendPropertyChanging();
			entity.tsysClient = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysModul")]
	public partial class tsysModul : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKModul;
		
		private System.Nullable<long> _FKModulGroup;
		
		private System.Nullable<int> _SortOrder;
		
		private string _Name;
		
		private System.Data.Linq.Binary _Image;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _FKUserCreated;
		
		private System.Nullable<System.DateTime> _ChangedOn;
		
		private System.Nullable<long> _FKUserChangedOn;
		
		private EntitySet<tsysCategory> _tsysCategory;
		
		private EntityRef<tsysModulGroup> _tsysModulGroup;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKModulChanging(long value);
    partial void OnPKModulChanged();
    partial void OnFKModulGroupChanging(System.Nullable<long> value);
    partial void OnFKModulGroupChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnFKUserCreatedChanging(System.Nullable<long> value);
    partial void OnFKUserCreatedChanged();
    partial void OnChangedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnChangedOnChanged();
    partial void OnFKUserChangedOnChanging(System.Nullable<long> value);
    partial void OnFKUserChangedOnChanged();
    #endregion
		
		public tsysModul()
		{
			this._tsysCategory = new EntitySet<tsysCategory>(new Action<tsysCategory>(this.attach_tsysCategory), new Action<tsysCategory>(this.detach_tsysCategory));
			this._tsysModulGroup = default(EntityRef<tsysModulGroup>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKModul", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKModul
		{
			get
			{
				return this._PKModul;
			}
			set
			{
				if ((this._PKModul != value))
				{
					this.OnPKModulChanging(value);
					this.SendPropertyChanging();
					this._PKModul = value;
					this.SendPropertyChanged("PKModul");
					this.OnPKModulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKModulGroup", DbType="BigInt")]
		public System.Nullable<long> FKModulGroup
		{
			get
			{
				return this._FKModulGroup;
			}
			set
			{
				if ((this._FKModulGroup != value))
				{
					if (this._tsysModulGroup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKModulGroupChanging(value);
					this.SendPropertyChanging();
					this._FKModulGroup = value;
					this.SendPropertyChanged("FKModulGroup");
					this.OnFKModulGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserCreated", DbType="BigInt")]
		public System.Nullable<long> FKUserCreated
		{
			get
			{
				return this._FKUserCreated;
			}
			set
			{
				if ((this._FKUserCreated != value))
				{
					this.OnFKUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._FKUserCreated = value;
					this.SendPropertyChanged("FKUserCreated");
					this.OnFKUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangedOn
		{
			get
			{
				return this._ChangedOn;
			}
			set
			{
				if ((this._ChangedOn != value))
				{
					this.OnChangedOnChanging(value);
					this.SendPropertyChanging();
					this._ChangedOn = value;
					this.SendPropertyChanged("ChangedOn");
					this.OnChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserChangedOn", DbType="BigInt")]
		public System.Nullable<long> FKUserChangedOn
		{
			get
			{
				return this._FKUserChangedOn;
			}
			set
			{
				if ((this._FKUserChangedOn != value))
				{
					this.OnFKUserChangedOnChanging(value);
					this.SendPropertyChanging();
					this._FKUserChangedOn = value;
					this.SendPropertyChanged("FKUserChangedOn");
					this.OnFKUserChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysModul_tsysCategory", Storage="_tsysCategory", ThisKey="PKModul", OtherKey="FKModul")]
		public EntitySet<tsysCategory> tsysCategory
		{
			get
			{
				return this._tsysCategory;
			}
			set
			{
				this._tsysCategory.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysModulGroup_tsysModul", Storage="_tsysModulGroup", ThisKey="FKModulGroup", OtherKey="PKModulGroup", IsForeignKey=true)]
		public tsysModulGroup tsysModulGroup
		{
			get
			{
				return this._tsysModulGroup.Entity;
			}
			set
			{
				tsysModulGroup previousValue = this._tsysModulGroup.Entity;
				if (((previousValue != value) 
							|| (this._tsysModulGroup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tsysModulGroup.Entity = null;
						previousValue.tsysModul.Remove(this);
					}
					this._tsysModulGroup.Entity = value;
					if ((value != null))
					{
						value.tsysModul.Add(this);
						this._FKModulGroup = value.PKModulGroup;
					}
					else
					{
						this._FKModulGroup = default(Nullable<long>);
					}
					this.SendPropertyChanged("tsysModulGroup");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tsysCategory(tsysCategory entity)
		{
			this.SendPropertyChanging();
			entity.tsysModul = this;
		}
		
		private void detach_tsysCategory(tsysCategory entity)
		{
			this.SendPropertyChanging();
			entity.tsysModul = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysModulGroup")]
	public partial class tsysModulGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKModulGroup;
		
		private System.Nullable<long> _FKClient;
		
		private System.Nullable<int> _SortOrder;
		
		private string _Name;
		
		private System.Data.Linq.Binary _Image;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _FKUserCreated;
		
		private System.Nullable<System.DateTime> _ChangedOn;
		
		private System.Nullable<long> _FKUserChangedOn;
		
		private EntitySet<tsysModul> _tsysModul;
		
		private EntityRef<tsysClient> _tsysClient;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKModulGroupChanging(long value);
    partial void OnPKModulGroupChanged();
    partial void OnFKClientChanging(System.Nullable<long> value);
    partial void OnFKClientChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnFKUserCreatedChanging(System.Nullable<long> value);
    partial void OnFKUserCreatedChanged();
    partial void OnChangedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnChangedOnChanged();
    partial void OnFKUserChangedOnChanging(System.Nullable<long> value);
    partial void OnFKUserChangedOnChanged();
    #endregion
		
		public tsysModulGroup()
		{
			this._tsysModul = new EntitySet<tsysModul>(new Action<tsysModul>(this.attach_tsysModul), new Action<tsysModul>(this.detach_tsysModul));
			this._tsysClient = default(EntityRef<tsysClient>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKModulGroup", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKModulGroup
		{
			get
			{
				return this._PKModulGroup;
			}
			set
			{
				if ((this._PKModulGroup != value))
				{
					this.OnPKModulGroupChanging(value);
					this.SendPropertyChanging();
					this._PKModulGroup = value;
					this.SendPropertyChanged("PKModulGroup");
					this.OnPKModulGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKClient", DbType="BigInt")]
		public System.Nullable<long> FKClient
		{
			get
			{
				return this._FKClient;
			}
			set
			{
				if ((this._FKClient != value))
				{
					if (this._tsysClient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKClientChanging(value);
					this.SendPropertyChanging();
					this._FKClient = value;
					this.SendPropertyChanged("FKClient");
					this.OnFKClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserCreated", DbType="BigInt")]
		public System.Nullable<long> FKUserCreated
		{
			get
			{
				return this._FKUserCreated;
			}
			set
			{
				if ((this._FKUserCreated != value))
				{
					this.OnFKUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._FKUserCreated = value;
					this.SendPropertyChanged("FKUserCreated");
					this.OnFKUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangedOn
		{
			get
			{
				return this._ChangedOn;
			}
			set
			{
				if ((this._ChangedOn != value))
				{
					this.OnChangedOnChanging(value);
					this.SendPropertyChanging();
					this._ChangedOn = value;
					this.SendPropertyChanged("ChangedOn");
					this.OnChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserChangedOn", DbType="BigInt")]
		public System.Nullable<long> FKUserChangedOn
		{
			get
			{
				return this._FKUserChangedOn;
			}
			set
			{
				if ((this._FKUserChangedOn != value))
				{
					this.OnFKUserChangedOnChanging(value);
					this.SendPropertyChanging();
					this._FKUserChangedOn = value;
					this.SendPropertyChanged("FKUserChangedOn");
					this.OnFKUserChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysModulGroup_tsysModul", Storage="_tsysModul", ThisKey="PKModulGroup", OtherKey="FKModulGroup")]
		public EntitySet<tsysModul> tsysModul
		{
			get
			{
				return this._tsysModul;
			}
			set
			{
				this._tsysModul.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysClient_tsysModulGroup", Storage="_tsysClient", ThisKey="FKClient", OtherKey="PKClient", IsForeignKey=true)]
		public tsysClient tsysClient
		{
			get
			{
				return this._tsysClient.Entity;
			}
			set
			{
				tsysClient previousValue = this._tsysClient.Entity;
				if (((previousValue != value) 
							|| (this._tsysClient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tsysClient.Entity = null;
						previousValue.tsysModulGroup.Remove(this);
					}
					this._tsysClient.Entity = value;
					if ((value != null))
					{
						value.tsysModulGroup.Add(this);
						this._FKClient = value.PKClient;
					}
					else
					{
						this._FKClient = default(Nullable<long>);
					}
					this.SendPropertyChanged("tsysClient");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tsysModul(tsysModul entity)
		{
			this.SendPropertyChanging();
			entity.tsysModulGroup = this;
		}
		
		private void detach_tsysModul(tsysModul entity)
		{
			this.SendPropertyChanging();
			entity.tsysModulGroup = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysSubCategory")]
	public partial class tsysSubCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKSubCategory;
		
		private System.Nullable<long> _FKCategory;
		
		private string _Name;
		
		private System.Data.Linq.Binary _Image;
		
		private System.Nullable<int> _SortOrder;
		
		private string _Assemblyname;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _FKUserCreated;
		
		private System.Nullable<System.DateTime> _ChangedOn;
		
		private System.Nullable<long> _FKUserChangedOn;
		
		private EntityRef<tsysCategory> _tsysCategory;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKSubCategoryChanging(long value);
    partial void OnPKSubCategoryChanged();
    partial void OnFKCategoryChanging(System.Nullable<long> value);
    partial void OnFKCategoryChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnAssemblynameChanging(string value);
    partial void OnAssemblynameChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnFKUserCreatedChanging(System.Nullable<long> value);
    partial void OnFKUserCreatedChanged();
    partial void OnChangedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnChangedOnChanged();
    partial void OnFKUserChangedOnChanging(System.Nullable<long> value);
    partial void OnFKUserChangedOnChanged();
    #endregion
		
		public tsysSubCategory()
		{
			this._tsysCategory = default(EntityRef<tsysCategory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKSubCategory", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKSubCategory
		{
			get
			{
				return this._PKSubCategory;
			}
			set
			{
				if ((this._PKSubCategory != value))
				{
					this.OnPKSubCategoryChanging(value);
					this.SendPropertyChanging();
					this._PKSubCategory = value;
					this.SendPropertyChanged("PKSubCategory");
					this.OnPKSubCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKCategory", DbType="BigInt")]
		public System.Nullable<long> FKCategory
		{
			get
			{
				return this._FKCategory;
			}
			set
			{
				if ((this._FKCategory != value))
				{
					if (this._tsysCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKCategoryChanging(value);
					this.SendPropertyChanging();
					this._FKCategory = value;
					this.SendPropertyChanged("FKCategory");
					this.OnFKCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assemblyname", DbType="NVarChar(255)")]
		public string Assemblyname
		{
			get
			{
				return this._Assemblyname;
			}
			set
			{
				if ((this._Assemblyname != value))
				{
					this.OnAssemblynameChanging(value);
					this.SendPropertyChanging();
					this._Assemblyname = value;
					this.SendPropertyChanged("Assemblyname");
					this.OnAssemblynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserCreated", DbType="BigInt")]
		public System.Nullable<long> FKUserCreated
		{
			get
			{
				return this._FKUserCreated;
			}
			set
			{
				if ((this._FKUserCreated != value))
				{
					this.OnFKUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._FKUserCreated = value;
					this.SendPropertyChanged("FKUserCreated");
					this.OnFKUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangedOn
		{
			get
			{
				return this._ChangedOn;
			}
			set
			{
				if ((this._ChangedOn != value))
				{
					this.OnChangedOnChanging(value);
					this.SendPropertyChanging();
					this._ChangedOn = value;
					this.SendPropertyChanged("ChangedOn");
					this.OnChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserChangedOn", DbType="BigInt")]
		public System.Nullable<long> FKUserChangedOn
		{
			get
			{
				return this._FKUserChangedOn;
			}
			set
			{
				if ((this._FKUserChangedOn != value))
				{
					this.OnFKUserChangedOnChanging(value);
					this.SendPropertyChanging();
					this._FKUserChangedOn = value;
					this.SendPropertyChanged("FKUserChangedOn");
					this.OnFKUserChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysCategory_tsysSubCategory", Storage="_tsysCategory", ThisKey="FKCategory", OtherKey="PKCategory", IsForeignKey=true)]
		public tsysCategory tsysCategory
		{
			get
			{
				return this._tsysCategory.Entity;
			}
			set
			{
				tsysCategory previousValue = this._tsysCategory.Entity;
				if (((previousValue != value) 
							|| (this._tsysCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tsysCategory.Entity = null;
						previousValue.tsysSubCategory.Remove(this);
					}
					this._tsysCategory.Entity = value;
					if ((value != null))
					{
						value.tsysSubCategory.Add(this);
						this._FKCategory = value.PKCategory;
					}
					else
					{
						this._FKCategory = default(Nullable<long>);
					}
					this.SendPropertyChanged("tsysCategory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_Wookie_Menu_0000")]
	public partial class v_Wookie_Menu_0000
	{
		
		private long _PKClient;
		
		private string _ClientName;
		
		private System.Data.Linq.Binary _ClientImage;
		
		private string _ModulGroupName;
		
		private System.Data.Linq.Binary _ModulGroupImage;
		
		private System.Nullable<int> _ModulGroupSortOrder;
		
		private string _ModulName;
		
		private System.Data.Linq.Binary _ModulImage;
		
		private System.Nullable<int> _ModulSortOrder;
		
		private System.Nullable<long> _FKExternal;
		
		private string _CategoryName;
		
		private System.Data.Linq.Binary _CategoryImage;
		
		private System.Nullable<int> _CategorySortOrder;
		
		private string _CategoryAssemblyname;
		
		private System.Nullable<long> _PKModulGroup;
		
		private System.Nullable<long> _PKModul;
		
		private System.Nullable<long> _PKCategory;
		
		private System.Nullable<long> _PKSubCategory;
		
		private string _SubCategoryName;
		
		private System.Data.Linq.Binary _SubCategoryImage;
		
		private System.Nullable<int> _SubCategorySortOrder;
		
		private string _SubCategoryAssemblyname;
		
		private string _Datasource;
		
		private string _InitialCatalog;
		
		private System.Nullable<bool> _PersistSecurityInfo;
		
		private string _UserID;
		
		private string _Password;
		
		public v_Wookie_Menu_0000()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKClient", DbType="BigInt NOT NULL")]
		public long PKClient
		{
			get
			{
				return this._PKClient;
			}
			set
			{
				if ((this._PKClient != value))
				{
					this._PKClient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="NVarChar(255)")]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this._ClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ClientImage
		{
			get
			{
				return this._ClientImage;
			}
			set
			{
				if ((this._ClientImage != value))
				{
					this._ClientImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulGroupName", DbType="NVarChar(50)")]
		public string ModulGroupName
		{
			get
			{
				return this._ModulGroupName;
			}
			set
			{
				if ((this._ModulGroupName != value))
				{
					this._ModulGroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulGroupImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ModulGroupImage
		{
			get
			{
				return this._ModulGroupImage;
			}
			set
			{
				if ((this._ModulGroupImage != value))
				{
					this._ModulGroupImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulGroupSortOrder", DbType="Int")]
		public System.Nullable<int> ModulGroupSortOrder
		{
			get
			{
				return this._ModulGroupSortOrder;
			}
			set
			{
				if ((this._ModulGroupSortOrder != value))
				{
					this._ModulGroupSortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulName", DbType="NVarChar(50)")]
		public string ModulName
		{
			get
			{
				return this._ModulName;
			}
			set
			{
				if ((this._ModulName != value))
				{
					this._ModulName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ModulImage
		{
			get
			{
				return this._ModulImage;
			}
			set
			{
				if ((this._ModulImage != value))
				{
					this._ModulImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulSortOrder", DbType="Int")]
		public System.Nullable<int> ModulSortOrder
		{
			get
			{
				return this._ModulSortOrder;
			}
			set
			{
				if ((this._ModulSortOrder != value))
				{
					this._ModulSortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKExternal", DbType="BigInt")]
		public System.Nullable<long> FKExternal
		{
			get
			{
				return this._FKExternal;
			}
			set
			{
				if ((this._FKExternal != value))
				{
					this._FKExternal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(50)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary CategoryImage
		{
			get
			{
				return this._CategoryImage;
			}
			set
			{
				if ((this._CategoryImage != value))
				{
					this._CategoryImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategorySortOrder", DbType="Int")]
		public System.Nullable<int> CategorySortOrder
		{
			get
			{
				return this._CategorySortOrder;
			}
			set
			{
				if ((this._CategorySortOrder != value))
				{
					this._CategorySortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryAssemblyname", DbType="NVarChar(255)")]
		public string CategoryAssemblyname
		{
			get
			{
				return this._CategoryAssemblyname;
			}
			set
			{
				if ((this._CategoryAssemblyname != value))
				{
					this._CategoryAssemblyname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKModulGroup", DbType="BigInt")]
		public System.Nullable<long> PKModulGroup
		{
			get
			{
				return this._PKModulGroup;
			}
			set
			{
				if ((this._PKModulGroup != value))
				{
					this._PKModulGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKModul", DbType="BigInt")]
		public System.Nullable<long> PKModul
		{
			get
			{
				return this._PKModul;
			}
			set
			{
				if ((this._PKModul != value))
				{
					this._PKModul = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKCategory", DbType="BigInt")]
		public System.Nullable<long> PKCategory
		{
			get
			{
				return this._PKCategory;
			}
			set
			{
				if ((this._PKCategory != value))
				{
					this._PKCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKSubCategory", DbType="BigInt")]
		public System.Nullable<long> PKSubCategory
		{
			get
			{
				return this._PKSubCategory;
			}
			set
			{
				if ((this._PKSubCategory != value))
				{
					this._PKSubCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoryName", DbType="NVarChar(50)")]
		public string SubCategoryName
		{
			get
			{
				return this._SubCategoryName;
			}
			set
			{
				if ((this._SubCategoryName != value))
				{
					this._SubCategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoryImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SubCategoryImage
		{
			get
			{
				return this._SubCategoryImage;
			}
			set
			{
				if ((this._SubCategoryImage != value))
				{
					this._SubCategoryImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategorySortOrder", DbType="Int")]
		public System.Nullable<int> SubCategorySortOrder
		{
			get
			{
				return this._SubCategorySortOrder;
			}
			set
			{
				if ((this._SubCategorySortOrder != value))
				{
					this._SubCategorySortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoryAssemblyname", DbType="NVarChar(255)")]
		public string SubCategoryAssemblyname
		{
			get
			{
				return this._SubCategoryAssemblyname;
			}
			set
			{
				if ((this._SubCategoryAssemblyname != value))
				{
					this._SubCategoryAssemblyname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datasource", DbType="NVarChar(255)")]
		public string Datasource
		{
			get
			{
				return this._Datasource;
			}
			set
			{
				if ((this._Datasource != value))
				{
					this._Datasource = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitialCatalog", DbType="NVarChar(255)")]
		public string InitialCatalog
		{
			get
			{
				return this._InitialCatalog;
			}
			set
			{
				if ((this._InitialCatalog != value))
				{
					this._InitialCatalog = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersistSecurityInfo", DbType="Bit")]
		public System.Nullable<bool> PersistSecurityInfo
		{
			get
			{
				return this._PersistSecurityInfo;
			}
			set
			{
				if ((this._PersistSecurityInfo != value))
				{
					this._PersistSecurityInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(255)")]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(255)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysClientElement")]
	public partial class tsysClientElement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKClientElement;
		
		private System.Nullable<long> _FKClient;
		
		private System.Nullable<long> _FKClientElement;
		
		private System.Nullable<long> _FKExternal;
		
		private System.Nullable<int> _SortOrder;
		
		private string _Name;
		
		private System.Data.Linq.Binary _Image;
		
		private string _Assemblyname;
		
		private EntitySet<tsysClientElement> _tsysClientElement2;
		
		private EntityRef<tsysClient> _tsysClient;
		
		private EntityRef<tsysClientElement> _tsysClientElement1;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKClientElementChanging(long value);
    partial void OnPKClientElementChanged();
    partial void OnFKClientChanging(System.Nullable<long> value);
    partial void OnFKClientChanged();
    partial void OnFKClientElementChanging(System.Nullable<long> value);
    partial void OnFKClientElementChanged();
    partial void OnFKExternalChanging(System.Nullable<long> value);
    partial void OnFKExternalChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    partial void OnAssemblynameChanging(string value);
    partial void OnAssemblynameChanged();
    #endregion
		
		public tsysClientElement()
		{
			this._tsysClientElement2 = new EntitySet<tsysClientElement>(new Action<tsysClientElement>(this.attach_tsysClientElement2), new Action<tsysClientElement>(this.detach_tsysClientElement2));
			this._tsysClient = default(EntityRef<tsysClient>);
			this._tsysClientElement1 = default(EntityRef<tsysClientElement>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKClientElement", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKClientElement
		{
			get
			{
				return this._PKClientElement;
			}
			set
			{
				if ((this._PKClientElement != value))
				{
					this.OnPKClientElementChanging(value);
					this.SendPropertyChanging();
					this._PKClientElement = value;
					this.SendPropertyChanged("PKClientElement");
					this.OnPKClientElementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKClient", DbType="BigInt")]
		public System.Nullable<long> FKClient
		{
			get
			{
				return this._FKClient;
			}
			set
			{
				if ((this._FKClient != value))
				{
					if (this._tsysClient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKClientChanging(value);
					this.SendPropertyChanging();
					this._FKClient = value;
					this.SendPropertyChanged("FKClient");
					this.OnFKClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKClientElement", DbType="BigInt")]
		public System.Nullable<long> FKClientElement
		{
			get
			{
				return this._FKClientElement;
			}
			set
			{
				if ((this._FKClientElement != value))
				{
					if (this._tsysClientElement1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKClientElementChanging(value);
					this.SendPropertyChanging();
					this._FKClientElement = value;
					this.SendPropertyChanged("FKClientElement");
					this.OnFKClientElementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKExternal", DbType="BigInt")]
		public System.Nullable<long> FKExternal
		{
			get
			{
				return this._FKExternal;
			}
			set
			{
				if ((this._FKExternal != value))
				{
					this.OnFKExternalChanging(value);
					this.SendPropertyChanging();
					this._FKExternal = value;
					this.SendPropertyChanged("FKExternal");
					this.OnFKExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assemblyname", DbType="NVarChar(255)")]
		public string Assemblyname
		{
			get
			{
				return this._Assemblyname;
			}
			set
			{
				if ((this._Assemblyname != value))
				{
					this.OnAssemblynameChanging(value);
					this.SendPropertyChanging();
					this._Assemblyname = value;
					this.SendPropertyChanged("Assemblyname");
					this.OnAssemblynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysClientElement_tsysClientElement", Storage="_tsysClientElement2", ThisKey="PKClientElement", OtherKey="FKClientElement")]
		public EntitySet<tsysClientElement> tsysClientElement2
		{
			get
			{
				return this._tsysClientElement2;
			}
			set
			{
				this._tsysClientElement2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysClient_tsysClientElement", Storage="_tsysClient", ThisKey="FKClient", OtherKey="PKClient", IsForeignKey=true)]
		public tsysClient tsysClient
		{
			get
			{
				return this._tsysClient.Entity;
			}
			set
			{
				tsysClient previousValue = this._tsysClient.Entity;
				if (((previousValue != value) 
							|| (this._tsysClient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tsysClient.Entity = null;
						previousValue.tsysClientElement.Remove(this);
					}
					this._tsysClient.Entity = value;
					if ((value != null))
					{
						value.tsysClientElement.Add(this);
						this._FKClient = value.PKClient;
					}
					else
					{
						this._FKClient = default(Nullable<long>);
					}
					this.SendPropertyChanged("tsysClient");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysClientElement_tsysClientElement", Storage="_tsysClientElement1", ThisKey="FKClientElement", OtherKey="PKClientElement", IsForeignKey=true)]
		public tsysClientElement tsysClientElement1
		{
			get
			{
				return this._tsysClientElement1.Entity;
			}
			set
			{
				tsysClientElement previousValue = this._tsysClientElement1.Entity;
				if (((previousValue != value) 
							|| (this._tsysClientElement1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tsysClientElement1.Entity = null;
						previousValue.tsysClientElement2.Remove(this);
					}
					this._tsysClientElement1.Entity = value;
					if ((value != null))
					{
						value.tsysClientElement2.Add(this);
						this._FKClientElement = value.PKClientElement;
					}
					else
					{
						this._FKClientElement = default(Nullable<long>);
					}
					this.SendPropertyChanged("tsysClientElement1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tsysClientElement2(tsysClientElement entity)
		{
			this.SendPropertyChanging();
			entity.tsysClientElement1 = this;
		}
		
		private void detach_tsysClientElement2(tsysClientElement entity)
		{
			this.SendPropertyChanging();
			entity.tsysClientElement1 = null;
		}
	}
}
#pragma warning restore 1591
