<?xml version="1.0" encoding="utf-8"?><Database Name="BS_PM_Master" Class="MenuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=BS_PM_Master;Integrated Security=True" SettingsObjectName="Wookie.Menu.Properties.Settings" SettingsPropertyName="BS_PM_MasterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tsysUser" Member="tsysUser">
    <Type Name="tsysUser">
      <Column Name="PKUser" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FKContact" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FKUserCreated" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FKUserChangedOn" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tsysClient" Member="tsysClient">
    <Type Name="tsysClient">
      <Column Name="PKClient" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Datasource" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="InitialCatalog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PersistSecurityInfo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ConnectRetryCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConnectRetryInterval" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConnectTimeout" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Encrypt" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FailoverPartner" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IntegratedSecurity" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Pooling" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PacketSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FKUserCreated" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FKUserChangedOn" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UniqueIdentifier" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="tsysClient_tsysClientElement" Member="tsysClientElement" ThisKey="PKClient" OtherKey="FKClient" Type="tsysClientElement" />
    </Type>
  </Table>
  <Table Name="dbo.tsysClientElement" Member="tsysClientElement">
    <Type Name="tsysClientElement">
      <Column Name="PKClientElement" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FKClient" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FKClientElement" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FKExternal" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Assemblyname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FKUserCreated" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FKUserChangedOn" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UniqueIdentifier" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="tsysClientElement_tsysClientElement" Member="tsysClientElement2" ThisKey="PKClientElement" OtherKey="FKClientElement" Type="tsysClientElement" />
      <Association Name="tsysClient_tsysClientElement" Member="tsysClient" ThisKey="FKClient" OtherKey="PKClient" Type="tsysClient" IsForeignKey="true" />
      <Association Name="tsysClientElement_tsysClientElement" Member="tsysClientElement1" ThisKey="FKClientElement" OtherKey="PKClientElement" Type="tsysClientElement" IsForeignKey="true" />
    </Type>
  </Table>
</Database>