#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wookie.Menu.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BS_PM_Master")]
	public partial class MenuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void InserttsysClient(tsysClient instance);
    partial void UpdatetsysClient(tsysClient instance);
    partial void DeletetsysClient(tsysClient instance);
    partial void InserttsysUser(tsysUser instance);
    partial void UpdatetsysUser(tsysUser instance);
    partial void DeletetsysUser(tsysUser instance);
    partial void InserttsysMenuItem(tsysMenuItem instance);
    partial void UpdatetsysMenuItem(tsysMenuItem instance);
    partial void DeletetsysMenuItem(tsysMenuItem instance);
    partial void InserttsysPage(tsysPage instance);
    partial void UpdatetsysPage(tsysPage instance);
    partial void DeletetsysPage(tsysPage instance);
    partial void InserttsysPageGroup(tsysPageGroup instance);
    partial void UpdatetsysPageGroup(tsysPageGroup instance);
    partial void DeletetsysPageGroup(tsysPageGroup instance);
    partial void InserttsysPageGroupItem(tsysPageGroupItem instance);
    partial void UpdatetsysPageGroupItem(tsysPageGroupItem instance);
    partial void DeletetsysPageGroupItem(tsysPageGroupItem instance);
    partial void InserttsysPageGroupItemCollection(tsysPageGroupItemCollection instance);
    partial void UpdatetsysPageGroupItemCollection(tsysPageGroupItemCollection instance);
    partial void DeletetsysPageGroupItemCollection(tsysPageGroupItemCollection instance);
    #endregion
		
		public MenuDataContext() : 
				base(global::Wookie.Menu.Properties.Settings.Default.BS_PM_MasterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MenuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<v_Wookie_Menu_0000> v_Wookie_Menu_0000
		{
			get
			{
				return this.GetTable<v_Wookie_Menu_0000>();
			}
		}
		
		public System.Data.Linq.Table<tsysClient> tsysClient
		{
			get
			{
				return this.GetTable<tsysClient>();
			}
		}
		
		public System.Data.Linq.Table<tsysUser> tsysUser
		{
			get
			{
				return this.GetTable<tsysUser>();
			}
		}
		
		public System.Data.Linq.Table<tsysMenuItem> tsysMenuItem
		{
			get
			{
				return this.GetTable<tsysMenuItem>();
			}
		}
		
		public System.Data.Linq.Table<tsysPage> tsysPage
		{
			get
			{
				return this.GetTable<tsysPage>();
			}
		}
		
		public System.Data.Linq.Table<tsysPageGroup> tsysPageGroup
		{
			get
			{
				return this.GetTable<tsysPageGroup>();
			}
		}
		
		public System.Data.Linq.Table<tsysPageGroupItem> tsysPageGroupItem
		{
			get
			{
				return this.GetTable<tsysPageGroupItem>();
			}
		}
		
		public System.Data.Linq.Table<tsysPageGroupItemCollection> tsysPageGroupItemCollection
		{
			get
			{
				return this.GetTable<tsysPageGroupItemCollection>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_Wookie_Menu_0000")]
	public partial class v_Wookie_Menu_0000
	{
		
		private long _PKClient;
		
		private string _ClientName;
		
		private string _ClientConnectionString;
		
		private System.Data.Linq.Binary _ClientSvgImage;
		
		private string _PageName;
		
		private System.Data.Linq.Binary _PageSvgImage;
		
		private string _PageGroupName;
		
		private System.Data.Linq.Binary _PageGroupSvgImage;
		
		private System.Nullable<long> _PKPageGroupItemCollection;
		
		private System.Nullable<long> _FKExternal;
		
		private string _PageGroupItemName;
		
		private System.Data.Linq.Binary _PageGroupItemSvgImage;
		
		private string _Assemblyname;
		
		private System.Nullable<long> _PKPage;
		
		private System.Nullable<long> _PKPageGroup;
		
		private System.Nullable<long> _PKPageGroupItem;
		
		private System.Nullable<bool> _PageGroupItemCollectionShowInMenu;
		
		private string _PageGroupItemCollectionName;
		
		private System.Data.Linq.Binary _PageGroupItemCollectionSvgImage;
		
		private string _MenuItemName;
		
		private System.Data.Linq.Binary _MenuItemSvgImage;
		
		private string _MenuItemAssemblyname;
		
		private System.Nullable<int> _PageSortOrder;
		
		private System.Nullable<int> _PageGroupSortOrder;
		
		private System.Nullable<int> _PageGroupItemCollectionSortOrder;
		
		private System.Nullable<int> _PageGroupItemSortOrder;
		
		private System.Nullable<int> _MenuItemSortOrder;
		
		public v_Wookie_Menu_0000()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKClient", DbType="BigInt NOT NULL")]
		public long PKClient
		{
			get
			{
				return this._PKClient;
			}
			set
			{
				if ((this._PKClient != value))
				{
					this._PKClient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="NVarChar(255)")]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this._ClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientConnectionString", DbType="NVarChar(255)")]
		public string ClientConnectionString
		{
			get
			{
				return this._ClientConnectionString;
			}
			set
			{
				if ((this._ClientConnectionString != value))
				{
					this._ClientConnectionString = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientSvgImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ClientSvgImage
		{
			get
			{
				return this._ClientSvgImage;
			}
			set
			{
				if ((this._ClientSvgImage != value))
				{
					this._ClientSvgImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageName", DbType="NVarChar(50)")]
		public string PageName
		{
			get
			{
				return this._PageName;
			}
			set
			{
				if ((this._PageName != value))
				{
					this._PageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageSvgImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PageSvgImage
		{
			get
			{
				return this._PageSvgImage;
			}
			set
			{
				if ((this._PageSvgImage != value))
				{
					this._PageSvgImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageGroupName", DbType="NVarChar(50)")]
		public string PageGroupName
		{
			get
			{
				return this._PageGroupName;
			}
			set
			{
				if ((this._PageGroupName != value))
				{
					this._PageGroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageGroupSvgImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PageGroupSvgImage
		{
			get
			{
				return this._PageGroupSvgImage;
			}
			set
			{
				if ((this._PageGroupSvgImage != value))
				{
					this._PageGroupSvgImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKPageGroupItemCollection", DbType="BigInt")]
		public System.Nullable<long> PKPageGroupItemCollection
		{
			get
			{
				return this._PKPageGroupItemCollection;
			}
			set
			{
				if ((this._PKPageGroupItemCollection != value))
				{
					this._PKPageGroupItemCollection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKExternal", DbType="BigInt")]
		public System.Nullable<long> FKExternal
		{
			get
			{
				return this._FKExternal;
			}
			set
			{
				if ((this._FKExternal != value))
				{
					this._FKExternal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageGroupItemName", DbType="NVarChar(50)")]
		public string PageGroupItemName
		{
			get
			{
				return this._PageGroupItemName;
			}
			set
			{
				if ((this._PageGroupItemName != value))
				{
					this._PageGroupItemName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageGroupItemSvgImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PageGroupItemSvgImage
		{
			get
			{
				return this._PageGroupItemSvgImage;
			}
			set
			{
				if ((this._PageGroupItemSvgImage != value))
				{
					this._PageGroupItemSvgImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assemblyname", DbType="NVarChar(255)")]
		public string Assemblyname
		{
			get
			{
				return this._Assemblyname;
			}
			set
			{
				if ((this._Assemblyname != value))
				{
					this._Assemblyname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKPage", DbType="BigInt")]
		public System.Nullable<long> PKPage
		{
			get
			{
				return this._PKPage;
			}
			set
			{
				if ((this._PKPage != value))
				{
					this._PKPage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKPageGroup", DbType="BigInt")]
		public System.Nullable<long> PKPageGroup
		{
			get
			{
				return this._PKPageGroup;
			}
			set
			{
				if ((this._PKPageGroup != value))
				{
					this._PKPageGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKPageGroupItem", DbType="BigInt")]
		public System.Nullable<long> PKPageGroupItem
		{
			get
			{
				return this._PKPageGroupItem;
			}
			set
			{
				if ((this._PKPageGroupItem != value))
				{
					this._PKPageGroupItem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageGroupItemCollectionShowInMenu", DbType="Bit")]
		public System.Nullable<bool> PageGroupItemCollectionShowInMenu
		{
			get
			{
				return this._PageGroupItemCollectionShowInMenu;
			}
			set
			{
				if ((this._PageGroupItemCollectionShowInMenu != value))
				{
					this._PageGroupItemCollectionShowInMenu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageGroupItemCollectionName", DbType="NVarChar(50)")]
		public string PageGroupItemCollectionName
		{
			get
			{
				return this._PageGroupItemCollectionName;
			}
			set
			{
				if ((this._PageGroupItemCollectionName != value))
				{
					this._PageGroupItemCollectionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageGroupItemCollectionSvgImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PageGroupItemCollectionSvgImage
		{
			get
			{
				return this._PageGroupItemCollectionSvgImage;
			}
			set
			{
				if ((this._PageGroupItemCollectionSvgImage != value))
				{
					this._PageGroupItemCollectionSvgImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemName", DbType="NVarChar(50)")]
		public string MenuItemName
		{
			get
			{
				return this._MenuItemName;
			}
			set
			{
				if ((this._MenuItemName != value))
				{
					this._MenuItemName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemSvgImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary MenuItemSvgImage
		{
			get
			{
				return this._MenuItemSvgImage;
			}
			set
			{
				if ((this._MenuItemSvgImage != value))
				{
					this._MenuItemSvgImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemAssemblyname", DbType="NVarChar(255)")]
		public string MenuItemAssemblyname
		{
			get
			{
				return this._MenuItemAssemblyname;
			}
			set
			{
				if ((this._MenuItemAssemblyname != value))
				{
					this._MenuItemAssemblyname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageSortOrder", DbType="Int")]
		public System.Nullable<int> PageSortOrder
		{
			get
			{
				return this._PageSortOrder;
			}
			set
			{
				if ((this._PageSortOrder != value))
				{
					this._PageSortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageGroupSortOrder", DbType="Int")]
		public System.Nullable<int> PageGroupSortOrder
		{
			get
			{
				return this._PageGroupSortOrder;
			}
			set
			{
				if ((this._PageGroupSortOrder != value))
				{
					this._PageGroupSortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageGroupItemCollectionSortOrder", DbType="Int")]
		public System.Nullable<int> PageGroupItemCollectionSortOrder
		{
			get
			{
				return this._PageGroupItemCollectionSortOrder;
			}
			set
			{
				if ((this._PageGroupItemCollectionSortOrder != value))
				{
					this._PageGroupItemCollectionSortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageGroupItemSortOrder", DbType="Int")]
		public System.Nullable<int> PageGroupItemSortOrder
		{
			get
			{
				return this._PageGroupItemSortOrder;
			}
			set
			{
				if ((this._PageGroupItemSortOrder != value))
				{
					this._PageGroupItemSortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemSortOrder", DbType="Int")]
		public System.Nullable<int> MenuItemSortOrder
		{
			get
			{
				return this._MenuItemSortOrder;
			}
			set
			{
				if ((this._MenuItemSortOrder != value))
				{
					this._MenuItemSortOrder = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysClient")]
	public partial class tsysClient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKClient;
		
		private string _Name;
		
		private System.Nullable<int> _SortOrder;
		
		private string _ConnectionString;
		
		private System.Data.Linq.Binary _SvgImage;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _FKUserCreated;
		
		private System.Nullable<System.DateTime> _ChangedOn;
		
		private System.Nullable<long> _FKUserChangedOn;
		
		private EntitySet<tsysPage> _tsysPage;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKClientChanging(long value);
    partial void OnPKClientChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnConnectionStringChanging(string value);
    partial void OnConnectionStringChanged();
    partial void OnSvgImageChanging(System.Data.Linq.Binary value);
    partial void OnSvgImageChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnFKUserCreatedChanging(System.Nullable<long> value);
    partial void OnFKUserCreatedChanged();
    partial void OnChangedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnChangedOnChanged();
    partial void OnFKUserChangedOnChanging(System.Nullable<long> value);
    partial void OnFKUserChangedOnChanged();
    #endregion
		
		public tsysClient()
		{
			this._tsysPage = new EntitySet<tsysPage>(new Action<tsysPage>(this.attach_tsysPage), new Action<tsysPage>(this.detach_tsysPage));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKClient", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKClient
		{
			get
			{
				return this._PKClient;
			}
			set
			{
				if ((this._PKClient != value))
				{
					this.OnPKClientChanging(value);
					this.SendPropertyChanging();
					this._PKClient = value;
					this.SendPropertyChanged("PKClient");
					this.OnPKClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConnectionString", DbType="NVarChar(255)")]
		public string ConnectionString
		{
			get
			{
				return this._ConnectionString;
			}
			set
			{
				if ((this._ConnectionString != value))
				{
					this.OnConnectionStringChanging(value);
					this.SendPropertyChanging();
					this._ConnectionString = value;
					this.SendPropertyChanged("ConnectionString");
					this.OnConnectionStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SvgImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SvgImage
		{
			get
			{
				return this._SvgImage;
			}
			set
			{
				if ((this._SvgImage != value))
				{
					this.OnSvgImageChanging(value);
					this.SendPropertyChanging();
					this._SvgImage = value;
					this.SendPropertyChanged("SvgImage");
					this.OnSvgImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserCreated", DbType="BigInt")]
		public System.Nullable<long> FKUserCreated
		{
			get
			{
				return this._FKUserCreated;
			}
			set
			{
				if ((this._FKUserCreated != value))
				{
					this.OnFKUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._FKUserCreated = value;
					this.SendPropertyChanged("FKUserCreated");
					this.OnFKUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangedOn
		{
			get
			{
				return this._ChangedOn;
			}
			set
			{
				if ((this._ChangedOn != value))
				{
					this.OnChangedOnChanging(value);
					this.SendPropertyChanging();
					this._ChangedOn = value;
					this.SendPropertyChanged("ChangedOn");
					this.OnChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserChangedOn", DbType="BigInt")]
		public System.Nullable<long> FKUserChangedOn
		{
			get
			{
				return this._FKUserChangedOn;
			}
			set
			{
				if ((this._FKUserChangedOn != value))
				{
					this.OnFKUserChangedOnChanging(value);
					this.SendPropertyChanging();
					this._FKUserChangedOn = value;
					this.SendPropertyChanged("FKUserChangedOn");
					this.OnFKUserChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysClient_tsysPage", Storage="_tsysPage", ThisKey="PKClient", OtherKey="FKClient")]
		public EntitySet<tsysPage> tsysPage
		{
			get
			{
				return this._tsysPage;
			}
			set
			{
				this._tsysPage.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tsysPage(tsysPage entity)
		{
			this.SendPropertyChanging();
			entity.tsysClient = this;
		}
		
		private void detach_tsysPage(tsysPage entity)
		{
			this.SendPropertyChanging();
			entity.tsysClient = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysUser")]
	public partial class tsysUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKUser;
		
		private System.Nullable<long> _FKContact;
		
		private string _Name;
		
		private string _Login;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _FKUserCreated;
		
		private System.Nullable<System.DateTime> _ChangedOn;
		
		private System.Nullable<long> _FKUserChangedOn;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKUserChanging(long value);
    partial void OnPKUserChanged();
    partial void OnFKContactChanging(System.Nullable<long> value);
    partial void OnFKContactChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnFKUserCreatedChanging(System.Nullable<long> value);
    partial void OnFKUserCreatedChanged();
    partial void OnChangedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnChangedOnChanged();
    partial void OnFKUserChangedOnChanging(System.Nullable<long> value);
    partial void OnFKUserChangedOnChanged();
    #endregion
		
		public tsysUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKUser", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKUser
		{
			get
			{
				return this._PKUser;
			}
			set
			{
				if ((this._PKUser != value))
				{
					this.OnPKUserChanging(value);
					this.SendPropertyChanging();
					this._PKUser = value;
					this.SendPropertyChanged("PKUser");
					this.OnPKUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKContact", DbType="BigInt")]
		public System.Nullable<long> FKContact
		{
			get
			{
				return this._FKContact;
			}
			set
			{
				if ((this._FKContact != value))
				{
					this.OnFKContactChanging(value);
					this.SendPropertyChanging();
					this._FKContact = value;
					this.SendPropertyChanged("FKContact");
					this.OnFKContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NVarChar(255)")]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserCreated", DbType="BigInt")]
		public System.Nullable<long> FKUserCreated
		{
			get
			{
				return this._FKUserCreated;
			}
			set
			{
				if ((this._FKUserCreated != value))
				{
					this.OnFKUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._FKUserCreated = value;
					this.SendPropertyChanged("FKUserCreated");
					this.OnFKUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangedOn
		{
			get
			{
				return this._ChangedOn;
			}
			set
			{
				if ((this._ChangedOn != value))
				{
					this.OnChangedOnChanging(value);
					this.SendPropertyChanging();
					this._ChangedOn = value;
					this.SendPropertyChanged("ChangedOn");
					this.OnChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserChangedOn", DbType="BigInt")]
		public System.Nullable<long> FKUserChangedOn
		{
			get
			{
				return this._FKUserChangedOn;
			}
			set
			{
				if ((this._FKUserChangedOn != value))
				{
					this.OnFKUserChangedOnChanging(value);
					this.SendPropertyChanging();
					this._FKUserChangedOn = value;
					this.SendPropertyChanged("FKUserChangedOn");
					this.OnFKUserChangedOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysMenuItem")]
	public partial class tsysMenuItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKMenuItem;
		
		private System.Nullable<long> _FKPageGroupItem;
		
		private string _Name;
		
		private System.Data.Linq.Binary _SvgImage;
		
		private string _Assemblyname;
		
		private System.Nullable<int> _SortOrder;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _FKUserCreated;
		
		private System.Nullable<System.DateTime> _ChangedOn;
		
		private System.Nullable<long> _FKUserChangedOn;
		
		private EntityRef<tsysPageGroupItem> _tsysPageGroupItem;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKMenuItemChanging(long value);
    partial void OnPKMenuItemChanged();
    partial void OnFKPageGroupItemChanging(System.Nullable<long> value);
    partial void OnFKPageGroupItemChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSvgImageChanging(System.Data.Linq.Binary value);
    partial void OnSvgImageChanged();
    partial void OnAssemblynameChanging(string value);
    partial void OnAssemblynameChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnFKUserCreatedChanging(System.Nullable<long> value);
    partial void OnFKUserCreatedChanged();
    partial void OnChangedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnChangedOnChanged();
    partial void OnFKUserChangedOnChanging(System.Nullable<long> value);
    partial void OnFKUserChangedOnChanged();
    #endregion
		
		public tsysMenuItem()
		{
			this._tsysPageGroupItem = default(EntityRef<tsysPageGroupItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKMenuItem", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKMenuItem
		{
			get
			{
				return this._PKMenuItem;
			}
			set
			{
				if ((this._PKMenuItem != value))
				{
					this.OnPKMenuItemChanging(value);
					this.SendPropertyChanging();
					this._PKMenuItem = value;
					this.SendPropertyChanged("PKMenuItem");
					this.OnPKMenuItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKPageGroupItem", DbType="BigInt")]
		public System.Nullable<long> FKPageGroupItem
		{
			get
			{
				return this._FKPageGroupItem;
			}
			set
			{
				if ((this._FKPageGroupItem != value))
				{
					if (this._tsysPageGroupItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKPageGroupItemChanging(value);
					this.SendPropertyChanging();
					this._FKPageGroupItem = value;
					this.SendPropertyChanged("FKPageGroupItem");
					this.OnFKPageGroupItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SvgImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SvgImage
		{
			get
			{
				return this._SvgImage;
			}
			set
			{
				if ((this._SvgImage != value))
				{
					this.OnSvgImageChanging(value);
					this.SendPropertyChanging();
					this._SvgImage = value;
					this.SendPropertyChanged("SvgImage");
					this.OnSvgImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assemblyname", DbType="NVarChar(255)")]
		public string Assemblyname
		{
			get
			{
				return this._Assemblyname;
			}
			set
			{
				if ((this._Assemblyname != value))
				{
					this.OnAssemblynameChanging(value);
					this.SendPropertyChanging();
					this._Assemblyname = value;
					this.SendPropertyChanged("Assemblyname");
					this.OnAssemblynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserCreated", DbType="BigInt")]
		public System.Nullable<long> FKUserCreated
		{
			get
			{
				return this._FKUserCreated;
			}
			set
			{
				if ((this._FKUserCreated != value))
				{
					this.OnFKUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._FKUserCreated = value;
					this.SendPropertyChanged("FKUserCreated");
					this.OnFKUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangedOn
		{
			get
			{
				return this._ChangedOn;
			}
			set
			{
				if ((this._ChangedOn != value))
				{
					this.OnChangedOnChanging(value);
					this.SendPropertyChanging();
					this._ChangedOn = value;
					this.SendPropertyChanged("ChangedOn");
					this.OnChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserChangedOn", DbType="BigInt")]
		public System.Nullable<long> FKUserChangedOn
		{
			get
			{
				return this._FKUserChangedOn;
			}
			set
			{
				if ((this._FKUserChangedOn != value))
				{
					this.OnFKUserChangedOnChanging(value);
					this.SendPropertyChanging();
					this._FKUserChangedOn = value;
					this.SendPropertyChanged("FKUserChangedOn");
					this.OnFKUserChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysPageGroupItem_tsysMenuItem", Storage="_tsysPageGroupItem", ThisKey="FKPageGroupItem", OtherKey="PKPageGroupItem", IsForeignKey=true)]
		public tsysPageGroupItem tsysPageGroupItem
		{
			get
			{
				return this._tsysPageGroupItem.Entity;
			}
			set
			{
				tsysPageGroupItem previousValue = this._tsysPageGroupItem.Entity;
				if (((previousValue != value) 
							|| (this._tsysPageGroupItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tsysPageGroupItem.Entity = null;
						previousValue.tsysMenuItem.Remove(this);
					}
					this._tsysPageGroupItem.Entity = value;
					if ((value != null))
					{
						value.tsysMenuItem.Add(this);
						this._FKPageGroupItem = value.PKPageGroupItem;
					}
					else
					{
						this._FKPageGroupItem = default(Nullable<long>);
					}
					this.SendPropertyChanged("tsysPageGroupItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysPage")]
	public partial class tsysPage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKPage;
		
		private System.Nullable<long> _FKClient;
		
		private System.Nullable<int> _SortOrder;
		
		private string _Name;
		
		private System.Data.Linq.Binary _SvgImage;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _FKUserCreated;
		
		private System.Nullable<System.DateTime> _ChangedOn;
		
		private System.Nullable<long> _FKUserChangedOn;
		
		private EntitySet<tsysPageGroup> _tsysPageGroup;
		
		private EntityRef<tsysClient> _tsysClient;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKPageChanging(long value);
    partial void OnPKPageChanged();
    partial void OnFKClientChanging(System.Nullable<long> value);
    partial void OnFKClientChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSvgImageChanging(System.Data.Linq.Binary value);
    partial void OnSvgImageChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnFKUserCreatedChanging(System.Nullable<long> value);
    partial void OnFKUserCreatedChanged();
    partial void OnChangedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnChangedOnChanged();
    partial void OnFKUserChangedOnChanging(System.Nullable<long> value);
    partial void OnFKUserChangedOnChanged();
    #endregion
		
		public tsysPage()
		{
			this._tsysPageGroup = new EntitySet<tsysPageGroup>(new Action<tsysPageGroup>(this.attach_tsysPageGroup), new Action<tsysPageGroup>(this.detach_tsysPageGroup));
			this._tsysClient = default(EntityRef<tsysClient>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKPage", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKPage
		{
			get
			{
				return this._PKPage;
			}
			set
			{
				if ((this._PKPage != value))
				{
					this.OnPKPageChanging(value);
					this.SendPropertyChanging();
					this._PKPage = value;
					this.SendPropertyChanged("PKPage");
					this.OnPKPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKClient", DbType="BigInt")]
		public System.Nullable<long> FKClient
		{
			get
			{
				return this._FKClient;
			}
			set
			{
				if ((this._FKClient != value))
				{
					if (this._tsysClient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKClientChanging(value);
					this.SendPropertyChanging();
					this._FKClient = value;
					this.SendPropertyChanged("FKClient");
					this.OnFKClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SvgImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SvgImage
		{
			get
			{
				return this._SvgImage;
			}
			set
			{
				if ((this._SvgImage != value))
				{
					this.OnSvgImageChanging(value);
					this.SendPropertyChanging();
					this._SvgImage = value;
					this.SendPropertyChanged("SvgImage");
					this.OnSvgImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserCreated", DbType="BigInt")]
		public System.Nullable<long> FKUserCreated
		{
			get
			{
				return this._FKUserCreated;
			}
			set
			{
				if ((this._FKUserCreated != value))
				{
					this.OnFKUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._FKUserCreated = value;
					this.SendPropertyChanged("FKUserCreated");
					this.OnFKUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangedOn
		{
			get
			{
				return this._ChangedOn;
			}
			set
			{
				if ((this._ChangedOn != value))
				{
					this.OnChangedOnChanging(value);
					this.SendPropertyChanging();
					this._ChangedOn = value;
					this.SendPropertyChanged("ChangedOn");
					this.OnChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserChangedOn", DbType="BigInt")]
		public System.Nullable<long> FKUserChangedOn
		{
			get
			{
				return this._FKUserChangedOn;
			}
			set
			{
				if ((this._FKUserChangedOn != value))
				{
					this.OnFKUserChangedOnChanging(value);
					this.SendPropertyChanging();
					this._FKUserChangedOn = value;
					this.SendPropertyChanged("FKUserChangedOn");
					this.OnFKUserChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysPage_tsysPageGroup", Storage="_tsysPageGroup", ThisKey="PKPage", OtherKey="FKPage")]
		public EntitySet<tsysPageGroup> tsysPageGroup
		{
			get
			{
				return this._tsysPageGroup;
			}
			set
			{
				this._tsysPageGroup.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysClient_tsysPage", Storage="_tsysClient", ThisKey="FKClient", OtherKey="PKClient", IsForeignKey=true)]
		public tsysClient tsysClient
		{
			get
			{
				return this._tsysClient.Entity;
			}
			set
			{
				tsysClient previousValue = this._tsysClient.Entity;
				if (((previousValue != value) 
							|| (this._tsysClient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tsysClient.Entity = null;
						previousValue.tsysPage.Remove(this);
					}
					this._tsysClient.Entity = value;
					if ((value != null))
					{
						value.tsysPage.Add(this);
						this._FKClient = value.PKClient;
					}
					else
					{
						this._FKClient = default(Nullable<long>);
					}
					this.SendPropertyChanged("tsysClient");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tsysPageGroup(tsysPageGroup entity)
		{
			this.SendPropertyChanging();
			entity.tsysPage = this;
		}
		
		private void detach_tsysPageGroup(tsysPageGroup entity)
		{
			this.SendPropertyChanging();
			entity.tsysPage = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysPageGroup")]
	public partial class tsysPageGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKPageGroup;
		
		private System.Nullable<long> _FKPage;
		
		private System.Nullable<int> _SortOrder;
		
		private string _Name;
		
		private System.Data.Linq.Binary _SvgImage;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _FKUserCreated;
		
		private System.Nullable<System.DateTime> _ChangedOn;
		
		private System.Nullable<long> _FKUserChangedOn;
		
		private EntitySet<tsysPageGroupItemCollection> _tsysPageGroupItemCollection;
		
		private EntityRef<tsysPage> _tsysPage;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKPageGroupChanging(long value);
    partial void OnPKPageGroupChanged();
    partial void OnFKPageChanging(System.Nullable<long> value);
    partial void OnFKPageChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSvgImageChanging(System.Data.Linq.Binary value);
    partial void OnSvgImageChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnFKUserCreatedChanging(System.Nullable<long> value);
    partial void OnFKUserCreatedChanged();
    partial void OnChangedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnChangedOnChanged();
    partial void OnFKUserChangedOnChanging(System.Nullable<long> value);
    partial void OnFKUserChangedOnChanged();
    #endregion
		
		public tsysPageGroup()
		{
			this._tsysPageGroupItemCollection = new EntitySet<tsysPageGroupItemCollection>(new Action<tsysPageGroupItemCollection>(this.attach_tsysPageGroupItemCollection), new Action<tsysPageGroupItemCollection>(this.detach_tsysPageGroupItemCollection));
			this._tsysPage = default(EntityRef<tsysPage>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKPageGroup", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKPageGroup
		{
			get
			{
				return this._PKPageGroup;
			}
			set
			{
				if ((this._PKPageGroup != value))
				{
					this.OnPKPageGroupChanging(value);
					this.SendPropertyChanging();
					this._PKPageGroup = value;
					this.SendPropertyChanged("PKPageGroup");
					this.OnPKPageGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKPage", DbType="BigInt")]
		public System.Nullable<long> FKPage
		{
			get
			{
				return this._FKPage;
			}
			set
			{
				if ((this._FKPage != value))
				{
					if (this._tsysPage.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKPageChanging(value);
					this.SendPropertyChanging();
					this._FKPage = value;
					this.SendPropertyChanged("FKPage");
					this.OnFKPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SvgImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SvgImage
		{
			get
			{
				return this._SvgImage;
			}
			set
			{
				if ((this._SvgImage != value))
				{
					this.OnSvgImageChanging(value);
					this.SendPropertyChanging();
					this._SvgImage = value;
					this.SendPropertyChanged("SvgImage");
					this.OnSvgImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserCreated", DbType="BigInt")]
		public System.Nullable<long> FKUserCreated
		{
			get
			{
				return this._FKUserCreated;
			}
			set
			{
				if ((this._FKUserCreated != value))
				{
					this.OnFKUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._FKUserCreated = value;
					this.SendPropertyChanged("FKUserCreated");
					this.OnFKUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangedOn
		{
			get
			{
				return this._ChangedOn;
			}
			set
			{
				if ((this._ChangedOn != value))
				{
					this.OnChangedOnChanging(value);
					this.SendPropertyChanging();
					this._ChangedOn = value;
					this.SendPropertyChanged("ChangedOn");
					this.OnChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserChangedOn", DbType="BigInt")]
		public System.Nullable<long> FKUserChangedOn
		{
			get
			{
				return this._FKUserChangedOn;
			}
			set
			{
				if ((this._FKUserChangedOn != value))
				{
					this.OnFKUserChangedOnChanging(value);
					this.SendPropertyChanging();
					this._FKUserChangedOn = value;
					this.SendPropertyChanged("FKUserChangedOn");
					this.OnFKUserChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysPageGroup_tsysPageGroupItemCollection", Storage="_tsysPageGroupItemCollection", ThisKey="PKPageGroup", OtherKey="FKPageGroup")]
		public EntitySet<tsysPageGroupItemCollection> tsysPageGroupItemCollection
		{
			get
			{
				return this._tsysPageGroupItemCollection;
			}
			set
			{
				this._tsysPageGroupItemCollection.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysPage_tsysPageGroup", Storage="_tsysPage", ThisKey="FKPage", OtherKey="PKPage", IsForeignKey=true)]
		public tsysPage tsysPage
		{
			get
			{
				return this._tsysPage.Entity;
			}
			set
			{
				tsysPage previousValue = this._tsysPage.Entity;
				if (((previousValue != value) 
							|| (this._tsysPage.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tsysPage.Entity = null;
						previousValue.tsysPageGroup.Remove(this);
					}
					this._tsysPage.Entity = value;
					if ((value != null))
					{
						value.tsysPageGroup.Add(this);
						this._FKPage = value.PKPage;
					}
					else
					{
						this._FKPage = default(Nullable<long>);
					}
					this.SendPropertyChanged("tsysPage");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tsysPageGroupItemCollection(tsysPageGroupItemCollection entity)
		{
			this.SendPropertyChanging();
			entity.tsysPageGroup = this;
		}
		
		private void detach_tsysPageGroupItemCollection(tsysPageGroupItemCollection entity)
		{
			this.SendPropertyChanging();
			entity.tsysPageGroup = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysPageGroupItem")]
	public partial class tsysPageGroupItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKPageGroupItem;
		
		private System.Nullable<long> _FKPageGroupItemCollection;
		
		private System.Nullable<long> _FKExternal;
		
		private string _Name;
		
		private System.Data.Linq.Binary _SvgImage;
		
		private string _Assemblyname;
		
		private System.Nullable<int> _SortOrder;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _FKUserCreated;
		
		private System.Nullable<System.DateTime> _ChangedOn;
		
		private System.Nullable<long> _FKUserChangedOn;
		
		private EntitySet<tsysMenuItem> _tsysMenuItem;
		
		private EntityRef<tsysPageGroupItemCollection> _tsysPageGroupItemCollection;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKPageGroupItemChanging(long value);
    partial void OnPKPageGroupItemChanged();
    partial void OnFKPageGroupItemCollectionChanging(System.Nullable<long> value);
    partial void OnFKPageGroupItemCollectionChanged();
    partial void OnFKExternalChanging(System.Nullable<long> value);
    partial void OnFKExternalChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSvgImageChanging(System.Data.Linq.Binary value);
    partial void OnSvgImageChanged();
    partial void OnAssemblynameChanging(string value);
    partial void OnAssemblynameChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnFKUserCreatedChanging(System.Nullable<long> value);
    partial void OnFKUserCreatedChanged();
    partial void OnChangedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnChangedOnChanged();
    partial void OnFKUserChangedOnChanging(System.Nullable<long> value);
    partial void OnFKUserChangedOnChanged();
    #endregion
		
		public tsysPageGroupItem()
		{
			this._tsysMenuItem = new EntitySet<tsysMenuItem>(new Action<tsysMenuItem>(this.attach_tsysMenuItem), new Action<tsysMenuItem>(this.detach_tsysMenuItem));
			this._tsysPageGroupItemCollection = default(EntityRef<tsysPageGroupItemCollection>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKPageGroupItem", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKPageGroupItem
		{
			get
			{
				return this._PKPageGroupItem;
			}
			set
			{
				if ((this._PKPageGroupItem != value))
				{
					this.OnPKPageGroupItemChanging(value);
					this.SendPropertyChanging();
					this._PKPageGroupItem = value;
					this.SendPropertyChanged("PKPageGroupItem");
					this.OnPKPageGroupItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKPageGroupItemCollection", DbType="BigInt")]
		public System.Nullable<long> FKPageGroupItemCollection
		{
			get
			{
				return this._FKPageGroupItemCollection;
			}
			set
			{
				if ((this._FKPageGroupItemCollection != value))
				{
					if (this._tsysPageGroupItemCollection.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKPageGroupItemCollectionChanging(value);
					this.SendPropertyChanging();
					this._FKPageGroupItemCollection = value;
					this.SendPropertyChanged("FKPageGroupItemCollection");
					this.OnFKPageGroupItemCollectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKExternal", DbType="BigInt")]
		public System.Nullable<long> FKExternal
		{
			get
			{
				return this._FKExternal;
			}
			set
			{
				if ((this._FKExternal != value))
				{
					this.OnFKExternalChanging(value);
					this.SendPropertyChanging();
					this._FKExternal = value;
					this.SendPropertyChanged("FKExternal");
					this.OnFKExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SvgImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SvgImage
		{
			get
			{
				return this._SvgImage;
			}
			set
			{
				if ((this._SvgImage != value))
				{
					this.OnSvgImageChanging(value);
					this.SendPropertyChanging();
					this._SvgImage = value;
					this.SendPropertyChanged("SvgImage");
					this.OnSvgImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assemblyname", DbType="NVarChar(255)")]
		public string Assemblyname
		{
			get
			{
				return this._Assemblyname;
			}
			set
			{
				if ((this._Assemblyname != value))
				{
					this.OnAssemblynameChanging(value);
					this.SendPropertyChanging();
					this._Assemblyname = value;
					this.SendPropertyChanged("Assemblyname");
					this.OnAssemblynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserCreated", DbType="BigInt")]
		public System.Nullable<long> FKUserCreated
		{
			get
			{
				return this._FKUserCreated;
			}
			set
			{
				if ((this._FKUserCreated != value))
				{
					this.OnFKUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._FKUserCreated = value;
					this.SendPropertyChanged("FKUserCreated");
					this.OnFKUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangedOn
		{
			get
			{
				return this._ChangedOn;
			}
			set
			{
				if ((this._ChangedOn != value))
				{
					this.OnChangedOnChanging(value);
					this.SendPropertyChanging();
					this._ChangedOn = value;
					this.SendPropertyChanged("ChangedOn");
					this.OnChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserChangedOn", DbType="BigInt")]
		public System.Nullable<long> FKUserChangedOn
		{
			get
			{
				return this._FKUserChangedOn;
			}
			set
			{
				if ((this._FKUserChangedOn != value))
				{
					this.OnFKUserChangedOnChanging(value);
					this.SendPropertyChanging();
					this._FKUserChangedOn = value;
					this.SendPropertyChanged("FKUserChangedOn");
					this.OnFKUserChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysPageGroupItem_tsysMenuItem", Storage="_tsysMenuItem", ThisKey="PKPageGroupItem", OtherKey="FKPageGroupItem")]
		public EntitySet<tsysMenuItem> tsysMenuItem
		{
			get
			{
				return this._tsysMenuItem;
			}
			set
			{
				this._tsysMenuItem.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysPageGroupItemCollection_tsysPageGroupItem", Storage="_tsysPageGroupItemCollection", ThisKey="FKPageGroupItemCollection", OtherKey="PKPageGroupItemCollection", IsForeignKey=true)]
		public tsysPageGroupItemCollection tsysPageGroupItemCollection
		{
			get
			{
				return this._tsysPageGroupItemCollection.Entity;
			}
			set
			{
				tsysPageGroupItemCollection previousValue = this._tsysPageGroupItemCollection.Entity;
				if (((previousValue != value) 
							|| (this._tsysPageGroupItemCollection.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tsysPageGroupItemCollection.Entity = null;
						previousValue.tsysPageGroupItem.Remove(this);
					}
					this._tsysPageGroupItemCollection.Entity = value;
					if ((value != null))
					{
						value.tsysPageGroupItem.Add(this);
						this._FKPageGroupItemCollection = value.PKPageGroupItemCollection;
					}
					else
					{
						this._FKPageGroupItemCollection = default(Nullable<long>);
					}
					this.SendPropertyChanged("tsysPageGroupItemCollection");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tsysMenuItem(tsysMenuItem entity)
		{
			this.SendPropertyChanging();
			entity.tsysPageGroupItem = this;
		}
		
		private void detach_tsysMenuItem(tsysMenuItem entity)
		{
			this.SendPropertyChanging();
			entity.tsysPageGroupItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tsysPageGroupItemCollection")]
	public partial class tsysPageGroupItemCollection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PKPageGroupItemCollection;
		
		private System.Nullable<long> _FKPageGroup;
		
		private System.Nullable<bool> _ShowInMenu;
		
		private string _Name;
		
		private System.Data.Linq.Binary _SvgImage;
		
		private System.Nullable<int> _SortOrder;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _FKUserCreated;
		
		private System.Nullable<System.DateTime> _ChangedOn;
		
		private System.Nullable<long> _FKUserChangedOn;
		
		private EntitySet<tsysPageGroupItem> _tsysPageGroupItem;
		
		private EntityRef<tsysPageGroup> _tsysPageGroup;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPKPageGroupItemCollectionChanging(long value);
    partial void OnPKPageGroupItemCollectionChanged();
    partial void OnFKPageGroupChanging(System.Nullable<long> value);
    partial void OnFKPageGroupChanged();
    partial void OnShowInMenuChanging(System.Nullable<bool> value);
    partial void OnShowInMenuChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSvgImageChanging(System.Data.Linq.Binary value);
    partial void OnSvgImageChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnFKUserCreatedChanging(System.Nullable<long> value);
    partial void OnFKUserCreatedChanged();
    partial void OnChangedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnChangedOnChanged();
    partial void OnFKUserChangedOnChanging(System.Nullable<long> value);
    partial void OnFKUserChangedOnChanged();
    #endregion
		
		public tsysPageGroupItemCollection()
		{
			this._tsysPageGroupItem = new EntitySet<tsysPageGroupItem>(new Action<tsysPageGroupItem>(this.attach_tsysPageGroupItem), new Action<tsysPageGroupItem>(this.detach_tsysPageGroupItem));
			this._tsysPageGroup = default(EntityRef<tsysPageGroup>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKPageGroupItemCollection", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PKPageGroupItemCollection
		{
			get
			{
				return this._PKPageGroupItemCollection;
			}
			set
			{
				if ((this._PKPageGroupItemCollection != value))
				{
					this.OnPKPageGroupItemCollectionChanging(value);
					this.SendPropertyChanging();
					this._PKPageGroupItemCollection = value;
					this.SendPropertyChanged("PKPageGroupItemCollection");
					this.OnPKPageGroupItemCollectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKPageGroup", DbType="BigInt")]
		public System.Nullable<long> FKPageGroup
		{
			get
			{
				return this._FKPageGroup;
			}
			set
			{
				if ((this._FKPageGroup != value))
				{
					if (this._tsysPageGroup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKPageGroupChanging(value);
					this.SendPropertyChanging();
					this._FKPageGroup = value;
					this.SendPropertyChanged("FKPageGroup");
					this.OnFKPageGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowInMenu", DbType="Bit")]
		public System.Nullable<bool> ShowInMenu
		{
			get
			{
				return this._ShowInMenu;
			}
			set
			{
				if ((this._ShowInMenu != value))
				{
					this.OnShowInMenuChanging(value);
					this.SendPropertyChanging();
					this._ShowInMenu = value;
					this.SendPropertyChanged("ShowInMenu");
					this.OnShowInMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SvgImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SvgImage
		{
			get
			{
				return this._SvgImage;
			}
			set
			{
				if ((this._SvgImage != value))
				{
					this.OnSvgImageChanging(value);
					this.SendPropertyChanging();
					this._SvgImage = value;
					this.SendPropertyChanged("SvgImage");
					this.OnSvgImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserCreated", DbType="BigInt")]
		public System.Nullable<long> FKUserCreated
		{
			get
			{
				return this._FKUserCreated;
			}
			set
			{
				if ((this._FKUserCreated != value))
				{
					this.OnFKUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._FKUserCreated = value;
					this.SendPropertyChanged("FKUserCreated");
					this.OnFKUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChangedOn
		{
			get
			{
				return this._ChangedOn;
			}
			set
			{
				if ((this._ChangedOn != value))
				{
					this.OnChangedOnChanging(value);
					this.SendPropertyChanging();
					this._ChangedOn = value;
					this.SendPropertyChanged("ChangedOn");
					this.OnChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUserChangedOn", DbType="BigInt")]
		public System.Nullable<long> FKUserChangedOn
		{
			get
			{
				return this._FKUserChangedOn;
			}
			set
			{
				if ((this._FKUserChangedOn != value))
				{
					this.OnFKUserChangedOnChanging(value);
					this.SendPropertyChanging();
					this._FKUserChangedOn = value;
					this.SendPropertyChanged("FKUserChangedOn");
					this.OnFKUserChangedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysPageGroupItemCollection_tsysPageGroupItem", Storage="_tsysPageGroupItem", ThisKey="PKPageGroupItemCollection", OtherKey="FKPageGroupItemCollection")]
		public EntitySet<tsysPageGroupItem> tsysPageGroupItem
		{
			get
			{
				return this._tsysPageGroupItem;
			}
			set
			{
				this._tsysPageGroupItem.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tsysPageGroup_tsysPageGroupItemCollection", Storage="_tsysPageGroup", ThisKey="FKPageGroup", OtherKey="PKPageGroup", IsForeignKey=true)]
		public tsysPageGroup tsysPageGroup
		{
			get
			{
				return this._tsysPageGroup.Entity;
			}
			set
			{
				tsysPageGroup previousValue = this._tsysPageGroup.Entity;
				if (((previousValue != value) 
							|| (this._tsysPageGroup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tsysPageGroup.Entity = null;
						previousValue.tsysPageGroupItemCollection.Remove(this);
					}
					this._tsysPageGroup.Entity = value;
					if ((value != null))
					{
						value.tsysPageGroupItemCollection.Add(this);
						this._FKPageGroup = value.PKPageGroup;
					}
					else
					{
						this._FKPageGroup = default(Nullable<long>);
					}
					this.SendPropertyChanged("tsysPageGroup");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tsysPageGroupItem(tsysPageGroupItem entity)
		{
			this.SendPropertyChanging();
			entity.tsysPageGroupItemCollection = this;
		}
		
		private void detach_tsysPageGroupItem(tsysPageGroupItem entity)
		{
			this.SendPropertyChanging();
			entity.tsysPageGroupItemCollection = null;
		}
	}
}
#pragma warning restore 1591
